riscv32: ptdump: Fix Fix build error
The error log:
arch/riscv/mm/ptdump.c:387:28: error: ‘pgtable_l5_enabled’ undeclared (first use in this function); did you mean ‘pgtable_l4_enabled’?
  387 |         pg_level[1].name = pgtable_l5_enabled ? "P4D" : "PGD";
      |                            ^~~~~~~~~~~~~~~~~~
      |                            pgtable_l4_enabled

Missing definition of pgtable_l5_enabled.

Signed-off-by: Chen Pei <cp0613@linux.alibaba.com>